name: Get Data from Website on a CRON Schedule

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  report:
    name: Get Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Python Script
        run: |
          python3 get_data.py
      - name: commit and push
        run: |
          git config --global user.email 'github-actions@github.com'
          git config --global user.name 'github-actions'
          git add .
          git commit -m "Update data"
          git push

