name: Get Data from Website on a CRON Schedule

on:
  push:
  workflow_dispatch:

jobs:
  report:
    name: Get Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run Python Script
        run: |
          python3 get_data.py
      - name: commit changes
        run: |
          git config --global user.email 'github-actions@github.com'
          git config --global user.name 'github-actions'
          git add .
          git commit -m "Update data"
          git push
